using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace WindowsBrowser.Sync.Crypto.Managed
{
    public enum DDGSyncCryptoResult
    {
        DDGSYNCCRYPTO_OK,
        DDGSYNCCRYPTO_UNKNOWN_ERROR,
        DDGSYNCCRYPTO_INVALID_USERID,
        DDGSYNCCRYPTO_INVALID_PASSWORD,
        DDGSYNCCRYPTO_CREATE_PRIMARY_KEY_FAILED,
        DDGSYNCCRYPTO_CREATE_PASSWORD_HASH_FAILED,
        DDGSYNCCRYPTO_CREATE_STRETCHED_PRIMARY_KEY_FAILED,
        DDGSYNCCRYPTO_CREATE_PROTECTED_SECRET_KEY_FAILED,
        DDGSYNCCRYPTO_ENCRYPTION_FAILED,
        DDGSYNCCRYPTO_DECRYPTION_FAILED,
        DDGSYNCCRYPTO_CONNECT_KEY_FAILED,
        DDGSYNCCRYPTO_SEAL_FAILED,
    }
}
