#include "DDGSyncCryptoSizes.h"

#include "../../native_lib/DDGSyncCrypto.h"

int ddgSyncGet_DDGSYNCCRYPTO_HASH_SIZE()
{
	return DDGSYNCCRYPTO_HASH_SIZE;
}

int ddgSyncGet_DDGSYNCCRYPTO_PRIMARY_KEY_SIZE()
{
	return DDGSYNCCRYPTO_PRIMARY_KEY_SIZE;
}

int ddgSyncGet_DDGSYNCCRYPTO_SECRET_KEY_SIZE()
{
	return DDGSYNCCRYPTO_SECRET_KEY_SIZE;
}

int ddgSyncGet_DDGSYNCCRYPTO_STRETCHED_PRIMARY_KEY_SIZE()
{
	return DDGSYNCCRYPTO_STRETCHED_PRIMARY_KEY_SIZE;
}

int ddgSyncGet_DDGSYNCCRYPTO_PROTECTED_SECRET_KEY_SIZE()
{
	return DDGSYNCCRYPTO_PROTECTED_SECRET_KEY_SIZE;
}

int ddgSyncGet_DDGSYNCCRYPTO_ENCRYPTED_EXTRA_BYTES_SIZE()
{
	return DDGSYNCCRYPTO_ENCRYPTED_EXTRA_BYTES_SIZE;
}

int ddgSyncGet_DDGSYNCCRYPTO_PUBLIC_KEY_SIZE()
{
	return DDGSYNCCRYPTO_PUBLIC_KEY_SIZE;
}

int ddgSyncGet_DDGSYNCCRYPTO_PRIVATE_KEY_SIZE()
{
	return DDGSYNCCRYPTO_PRIVATE_KEY_SIZE;
}

int ddgSyncGet_DDGSYNCCRYPTO_SEAL_EXTRA_BYTES_SIZE()
{
	return DDGSYNCCRYPTO_SEAL_EXTRA_BYTES_SIZE;
}